// Fichier généré le 2026-07-19 13:55:15
const data = {
    "niveau1": {
        "003": [
            {"nom": "AÉROTHERME A-003", "code": "A-003", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-4", "MARQUE": "ROSEMEX", "MODÈLE": "H-18", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,10", "DÉBIT AIR (L/S)": "217,00", "PUISSANCE (KW)": "4,022107474472", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,05", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-4"}},
            {"nom": "ROBINET MOTORISÉ RM-003A", "code": "RM-003A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "48,33", "DIAMÈTRE (MM)": "48,33", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-003B", "code": "RM-003B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}}
        ],
        "004": [
            {"nom": "AÉROTHERME A-004", "code": "A-004", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-4", "MARQUE": "ROSEMEX", "MODÈLE": "H-18", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,10", "DÉBIT AIR (L/S)": "217,00", "PUISSANCE (KW)": "4,022107474472", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,05", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-4"}},
            {"nom": "ROBINET MOTORISÉ RM-004", "code": "RM-004", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "48,33", "DIAMÈTRE (MM)": "48,33", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}}
        ],
        "007": [
            {"nom": "AÉROTHERME A-007A", "code": "A-007A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-5", "MARQUE": "ROSEMEX", "MODÈLE": "H-70", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,32", "DÉBIT AIR (L/S)": "696,00", "PUISSANCE (KW)": "12,79401791009", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,16", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-5"}},
            {"nom": "AÉROTHERME A-007B", "code": "A-007B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-5", "MARQUE": "ROSEMEX", "MODÈLE": "H-70", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,32", "DÉBIT AIR (L/S)": "696,00", "PUISSANCE (KW)": "12,79401791009", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,16", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-5"}},
            {"nom": "AÉROCONVECTEUR C-007A", "code": "C-007A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-5", "MARQUE": "ROSEMEX", "MODÈLE": "F-300-A", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-007-0", "DÉBIT LIQUIDE (L/S)": "0,1", "DÉBIT AIR (L/S)": "94", "PUISSANCE (KW)": "4,129078417942", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,07", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-5"}},
            {"nom": "AÉROCONVECTEUR C-007B", "code": "C-007B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-5", "MARQUE": "ROSEMEX", "MODÈLE": "F-300-A", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-007-0", "DÉBIT LIQUIDE (L/S)": "0,1", "DÉBIT AIR (L/S)": "94", "PUISSANCE (KW)": "4,129078417942", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,07", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-5"}},
            {"nom": "ROBINET PRISE D'EAU INTÉRIEUR RA-1", "code": "RA-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "Z1341", "RÉSEAU DE TUYAUTERIE": "Eau Froide Service", "FT / DA": "FT-MEC017-0"}},
            {"nom": "ROBINET MOTORISÉ RM-007A", "code": "RM-007A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B318", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,90", "PERTE DE PRESSION (KPA)": "25,37", "DIAMÈTRE (MM)": "25,37", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-007B", "code": "RM-007B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B312", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,48", "PERTE DE PRESSION (KPA)": "44,33", "DIAMÈTRE (MM)": "44,33", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-007C", "code": "RM-007C", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-007D", "code": "RM-007D", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-007E", "code": "RM-007E", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-J", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,32", "PERTE DE PRESSION (KPA)": "60,33", "DIAMÈTRE (MM)": "60,33", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-007F", "code": "RM-007F", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-J", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,32", "PERTE DE PRESSION (KPA)": "60,33", "DIAMÈTRE (MM)": "60,33", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-007G", "code": "RM-007G", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "51,09", "DIAMÈTRE (MM)": "51,09", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-007H", "code": "RM-007H", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "51,09", "DIAMÈTRE (MM)": "51,09", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "LAVE AUTO ", "code": "", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique de Prod", "MARQUE": "Mrs CLEAN", "MODÈLE": "2000"}},
            {"nom": "Ventilateur VE-10", "code": "VE-10", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-5", "MODÈLE": "ACME XD137EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVE-10, POT-VE-10"}},
            {"nom": "Unité de ventilation UV-01", "code": "UV-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-5", "MODÈLE": "ALDES PA20", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "Ctrl-Int-UV-01"}},
            {"nom": "Panneau de Distribution PE-5", "code": "PE-5", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PE-1", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "PD-1"}},
            {"nom": "Démarreur Moteur DVE-10", "code": "DVE-10", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-5"}},
            {"nom": "Variateur de vitesse POT-VE-10", "code": "POT-VE-10", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Contrôle Interne Ctrl-Int-UV-01", "code": "Ctrl-Int-UV-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité/Contrôle", "Prérequis": "PE-5"}}
        ],
        "011": [
            {"nom": "AÉROTHERME A-011", "code": "A-011", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-4", "MARQUE": "ROSEMEX", "MODÈLE": "H-32", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,16", "DÉBIT AIR (L/S)": "342,00", "PUISSANCE (KW)": "6,533433541854", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,08", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-4"}},
            {"nom": "DRAINS DE PLANCHER AS-1", "code": "AS-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-B5", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "DRAINS DE PLANCHER AS-2", "code": "AS-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-BF", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "ROBINET MOTORISÉ RM-011A", "code": "RM-011A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B213", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,62", "PERTE DE PRESSION (KPA)": "30,68", "DIAMÈTRE (MM)": "30,68", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-011B", "code": "RM-011B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-J", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,16", "PERTE DE PRESSION (KPA)": "31,58", "DIAMÈTRE (MM)": "31,58", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-011C", "code": "RM-011C", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-011D", "code": "RM-011D", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-011E", "code": "RM-011E", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-07", "code": "SC-07", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BD1202B", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "VA-07", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,62", "PERTE DE PRESSION (KPA)": "34,6", "PUISSANCE (KW)": "25,503924420794", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "Vérification d'état": "RIC-BAT632-7"}},
            {"nom": "Ventilateur VA-07", "code": "VA-07", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-4", "MODÈLE": "ACME XD137EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVA-07, POT-VA-07"}},
            {"nom": "Ventilateur VE-05", "code": "VE-05", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-4", "MODÈLE": "ACME XD100EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVE-05, POT-VE-05"}},
            {"nom": "Ventilateur VE-07", "code": "VE-07", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-4", "MODÈLE": "ACME XD120EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVE-07, POT-VE-07"}},
            {"nom": "Ventilateur VE-13", "code": "VE-13", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-4", "MODÈLE": "ACME XD161EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVE-13, POT-VE-13"}},
            {"nom": "Démarreur Moteur DVA-07", "code": "DVA-07", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-4"}},
            {"nom": "Variateur de vitesse POT-VA-07", "code": "POT-VA-07", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Démarreur Moteur DVE-05", "code": "DVE-05", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-4"}},
            {"nom": "Variateur de vitesse POT-VE-05", "code": "POT-VE-05", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Démarreur Moteur DVE-07", "code": "DVE-07", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-4"}},
            {"nom": "Variateur de vitesse POT-VE-07", "code": "POT-VE-07", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Démarreur Moteur DVE-13", "code": "DVE-13", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-4"}},
            {"nom": "Variateur de vitesse POT-VE-13", "code": "POT-VE-13", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}}
        ],
        "013": [
            {"nom": "AÉROTHERME A-013", "code": "A-013", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-4", "MARQUE": "ROSEMEX", "MODÈLE": "H-18", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,10", "DÉBIT AIR (L/S)": "217,00", "PUISSANCE (KW)": "4,022107474472", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,05", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-4"}},
            {"nom": "CUVE CU-2", "code": "CU-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "CAN-AQUA", "MODÈLE": "CA-EUPS-1818", "RÉSEAU DE TUYAUTERIE": "Eau Chaude Potable & Eau Froide Potable & Évent", "FT / DA": "FT-MEC011-0", "Vérification d'état": "FT-MEC-011"}},
            {"nom": "ROBINET MOTORISÉ RM-013A", "code": "RM-013A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B212", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,38", "PERTE DE PRESSION (KPA)": "27,65", "DIAMÈTRE (MM)": "27,65", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-013B", "code": "RM-013B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "48,33", "DIAMÈTRE (MM)": "48,33", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-05", "code": "SC-05", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BD1102B", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "VA-05", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,38", "PERTE DE PRESSION (KPA)": "27,5", "PUISSANCE (KW)": "14,829103475722", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "Vérification d'état": "RIC-BAT632-7"}},
            {"nom": "Ventilateur VA-05", "code": "VA-05", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-4", "MODÈLE": "ACME XD137EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVA-05, POT-VA-05"}},
            {"nom": "Démarreur Moteur DVA-05", "code": "DVA-05", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-4"}},
            {"nom": "Variateur de vitesse POT-VA-05", "code": "POT-VA-05", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}}
        ],
        "014": [
            {"nom": "AÉROTHERME A-014", "code": "A-014", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-4", "MARQUE": "ROSEMEX", "MODÈLE": "H-18", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,10", "DÉBIT AIR (L/S)": "217,00", "PUISSANCE (KW)": "4,022107474472", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,05", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-4"}},
            {"nom": "ROBINET MOTORISÉ RM-014A", "code": "RM-014A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B209", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "27,58", "DIAMÈTRE (MM)": "27,58", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-014B", "code": "RM-014B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "48,33", "DIAMÈTRE (MM)": "48,33", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-014C", "code": "RM-014C", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-06", "code": "SC-06", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BB0601B", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "VA-06", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "2,1", "PUISSANCE (KW)": "4,124389280694", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "Vérification d'état": "RIC-BAT632-7"}},
            {"nom": "Ventilateur VA-06", "code": "VA-06", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-4", "MODÈLE": "ACME XD161EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVA-06, POT-VA-06"}},
            {"nom": "Ventilateur VE-06", "code": "VE-06", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-4", "MODÈLE": "ACME XD161EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVE-06, POT-VE-06"}},
            {"nom": "Permutateur Automatique PM-2", "code": "PM-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "P-054"}},
            {"nom": "Démarreur Moteur DVA-06", "code": "DVA-06", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-4"}},
            {"nom": "Variateur de vitesse POT-VA-06", "code": "POT-VA-06", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Démarreur Moteur DVE-06", "code": "DVE-06", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-4"}},
            {"nom": "Variateur de vitesse POT-VE-06", "code": "POT-VE-06", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}}
        ],
        "016": [
            {"nom": "AÉROTHERME A-016A", "code": "A-016A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-7", "MARQUE": "ROSEMEX", "MODÈLE": "H-32", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,16", "DÉBIT AIR (L/S)": "342,00", "PUISSANCE (KW)": "6,533433541854", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,08", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-7"}},
            {"nom": "AÉROTHERME A-016B", "code": "A-016B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-7", "MARQUE": "ROSEMEX", "MODÈLE": "H-32", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,16", "DÉBIT AIR (L/S)": "342,00", "PUISSANCE (KW)": "6,533433541854", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,08", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-7"}},
            {"nom": "DRAINS DE PLANCHER AS-1", "code": "AS-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-B5", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "DOUCHE OCULAIRE DO-1", "code": "DO-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "BRADLEY", "MODÈLE": "S19-690", "RÉSEAU DE TUYAUTERIE": "N/A", "FT / DA": "FT-MEC016-A"}},
            {"nom": "ROBINET PRISE D'EAU INTÉRIEUR RA-1", "code": "RA-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "Z1341", "RÉSEAU DE TUYAUTERIE": "Eau Froide Service", "FT / DA": "FT-MEC017-0"}},
            {"nom": "ROBINET MOTORISÉ RM-016A", "code": "RM-016A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B210", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,18", "PERTE DE PRESSION (KPA)": "40,27", "DIAMÈTRE (MM)": "40,27", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-016B", "code": "RM-016B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-016C", "code": "RM-016C", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-016D", "code": "RM-016D", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-016E", "code": "RM-016E", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-J", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,16", "PERTE DE PRESSION (KPA)": "31,58", "DIAMÈTRE (MM)": "31,58", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-016F", "code": "RM-016F", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-J", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,16", "PERTE DE PRESSION (KPA)": "31,58", "DIAMÈTRE (MM)": "31,58", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-016G", "code": "RM-016G", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "F6100HD", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "DÉBIT LIQUIDE (L/S)": "5,05", "PERTE DE PRESSION (KPA)": "0,12", "DIAMÈTRE (MM)": "0,12", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-016H", "code": "RM-016H", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "F6100HD", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "DÉBIT LIQUIDE (L/S)": "5,05", "PERTE DE PRESSION (KPA)": "0,12", "DIAMÈTRE (MM)": "0,12", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-016I", "code": "RM-016I", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "F7100HD", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "DÉBIT LIQUIDE (L/S)": "15,14", "PERTE DE PRESSION (KPA)": "7,51", "DIAMÈTRE (MM)": "7,51", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-01", "code": "SC-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BS1001C", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "VA-01", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,18", "PERTE DE PRESSION (KPA)": "17,0", "PUISSANCE (KW)": "6,11785875325", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "68", "Vérification d'état": "RIC-BAT632-7"}},
            {"nom": "ÉCHANGEUR ", "code": "", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "0", "MARQUE": "TOROMONT", "MODÈLE": "AB-2005", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "FT / DA": "HQ-Toromont-Éch-3508", "Vérification d'état": "RIC-BAT632-12"}},
            {"nom": "Ventilateur VA-01", "code": "VA-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-7", "MARQUE": "Arbre", "MODÈLE": "ACME XD137EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVA-01, POT-VA-01"}},
            {"nom": "Unité de ventilation UV-04", "code": "UV-04", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "TVRB1", "MODÈLE": "Dakin CAH024GVBM", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Unité de ventilation UV-05", "code": "UV-05", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "TVRB1", "MODÈLE": "Dakin CAH024GVBM", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Panneau de Distribution PE-7", "code": "PE-7", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PD-A1", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "PD-A1"}},
            {"nom": "Panneau de Distribution PD-A1", "code": "PD-A1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "P-054", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "P-054"}},
            {"nom": "Démarreur Moteur DVA-01", "code": "DVA-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-7"}},
            {"nom": "Variateur de vitesse POT-VA-01", "code": "POT-VA-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}}
        ],
        "017": [
            {"nom": "AÉROTHERME A-017A", "code": "A-017A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-8", "MARQUE": "ROSEMEX", "MODÈLE": "H-32", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,16", "DÉBIT AIR (L/S)": "342,00", "PUISSANCE (KW)": "6,533433541854", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,08", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-8"}},
            {"nom": "AÉROTHERME A-017B", "code": "A-017B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-8", "MARQUE": "ROSEMEX", "MODÈLE": "H-32", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,16", "DÉBIT AIR (L/S)": "342,00", "PUISSANCE (KW)": "6,533433541854", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,08", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-8"}},
            {"nom": "DRAINS DE PLANCHER AS-1", "code": "AS-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-B5", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "DOUCHE OCULAIRE DO-1", "code": "DO-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "BRADLEY", "MODÈLE": "S19-690", "RÉSEAU DE TUYAUTERIE": "N/A", "FT / DA": "FT-MEC016-A"}},
            {"nom": "ROBINET PRISE D'EAU INTÉRIEUR RA-1", "code": "RA-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "Z1341", "RÉSEAU DE TUYAUTERIE": "Eau Froide Service", "FT / DA": "FT-MEC017-0"}},
            {"nom": "ROBINET MOTORISÉ RM-017A", "code": "RM-017A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B210", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,18", "PERTE DE PRESSION (KPA)": "40,27", "DIAMÈTRE (MM)": "40,27", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-017B", "code": "RM-017B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-017C", "code": "RM-017C", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-017D", "code": "RM-017D", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-017E", "code": "RM-017E", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-J", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,16", "PERTE DE PRESSION (KPA)": "31,58", "DIAMÈTRE (MM)": "31,58", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-017F", "code": "RM-017F", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-J", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,16", "PERTE DE PRESSION (KPA)": "31,58", "DIAMÈTRE (MM)": "31,58", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-017G", "code": "RM-017G", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "F6100HD", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "DÉBIT LIQUIDE (L/S)": "5,05", "PERTE DE PRESSION (KPA)": "0,12", "DIAMÈTRE (MM)": "0,12", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-017H", "code": "RM-017H", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "F6100HD", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "DÉBIT LIQUIDE (L/S)": "5,05", "PERTE DE PRESSION (KPA)": "0,12", "DIAMÈTRE (MM)": "0,12", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-02", "code": "SC-02", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BS1001C", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "VA-02", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,18", "PERTE DE PRESSION (KPA)": "17,0", "PUISSANCE (KW)": "6,11785875325", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "68", "Vérification d'état": "RIC-BAT632-7"}},
            {"nom": "ÉCHANGEUR ", "code": "", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "0", "MARQUE": "TOROMONT", "MODÈLE": "AB-2005", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "FT / DA": "HQ-Toromont-Éch-3508"}},
            {"nom": "Ventilateur VA-02", "code": "VA-02", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-8", "MODÈLE": "ACME XD137EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVA-02, POT-VA-02"}},
            {"nom": "Unité de ventilation UV-06", "code": "UV-06", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "TVRB2", "MODÈLE": "Dakin CAH024GVBM", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Unité de ventilation UV-07", "code": "UV-07", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "TVRB2", "MODÈLE": "Dakin CAH024GVBM", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Panneau de Distribution PE-8", "code": "PE-8", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PD-A2", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "PD-A2"}},
            {"nom": "Panneau de Distribution PD-A2", "code": "PD-A2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "P-054", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "P-054"}},
            {"nom": "Démarreur Moteur DVA-02", "code": "DVA-02", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-8"}},
            {"nom": "Variateur de vitesse POT-VA-02", "code": "POT-VA-02", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}}
        ],
        "018": [
            {"nom": "AÉROTHERME A-018A", "code": "A-018A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-9", "MARQUE": "ROSEMEX", "MODÈLE": "H-32", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,16", "DÉBIT AIR (L/S)": "342,00", "PUISSANCE (KW)": "6,533433541854", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,08", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-9"}},
            {"nom": "AÉROTHERME A-018B", "code": "A-018B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-9", "MARQUE": "ROSEMEX", "MODÈLE": "H-32", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,16", "DÉBIT AIR (L/S)": "342,00", "PUISSANCE (KW)": "6,533433541854", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,08", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-9"}},
            {"nom": "DRAINS DE PLANCHER AS-1", "code": "AS-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-B5", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "DOUCHE OCULAIRE DO-1", "code": "DO-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "BRADLEY", "MODÈLE": "S19-690", "RÉSEAU DE TUYAUTERIE": "N/A", "FT / DA": "FT-MEC016-A"}},
            {"nom": "ROBINET PRISE D'EAU INTÉRIEUR RA-1", "code": "RA-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "Z1341", "RÉSEAU DE TUYAUTERIE": "Eau Froide Service", "FT / DA": "FT-MEC017-0"}},
            {"nom": "ROBINET MOTORISÉ RM-018A", "code": "RM-018A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B210", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,18", "PERTE DE PRESSION (KPA)": "40,27", "DIAMÈTRE (MM)": "40,27", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-018B", "code": "RM-018B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-018C", "code": "RM-018C", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-018D", "code": "RM-018D", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-018E", "code": "RM-018E", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-J", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,16", "PERTE DE PRESSION (KPA)": "31,58", "DIAMÈTRE (MM)": "31,58", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-018F", "code": "RM-018F", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-J", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,16", "PERTE DE PRESSION (KPA)": "31,58", "DIAMÈTRE (MM)": "31,58", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-018G", "code": "RM-018G", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "F6100HD", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "DÉBIT LIQUIDE (L/S)": "5,05", "PERTE DE PRESSION (KPA)": "0,12", "DIAMÈTRE (MM)": "0,12", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-018H", "code": "RM-018H", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "F6100HD", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "DÉBIT LIQUIDE (L/S)": "5,05", "PERTE DE PRESSION (KPA)": "0,12", "DIAMÈTRE (MM)": "0,12", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-03", "code": "SC-03", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BS1001C", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "VA-03", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,18", "PERTE DE PRESSION (KPA)": "17,0", "PUISSANCE (KW)": "6,11785875325", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "68", "Vérification d'état": "RIC-BAT632-7"}},
            {"nom": "ÉCHANGEUR ", "code": "", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "0", "MARQUE": "TOROMONT", "MODÈLE": "AB-2006", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "FT / DA": "HQ-Toromont-Éch-3512"}},
            {"nom": "Ventilateur VA-03", "code": "VA-03", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-9", "MODÈLE": "ACME XD137EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVA-03, POT-VA-03"}},
            {"nom": "Unité de ventilation UV-08", "code": "UV-08", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "TVRB3", "MODÈLE": "Dakin CAH024GVBM", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Unité de ventilation UV-09", "code": "UV-09", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "TVRB3", "MODÈLE": "Dakin CAH024GVBM", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Panneau de Distribution PE-9", "code": "PE-9", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PD-A3", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "PD-A3"}},
            {"nom": "Panneau de Distribution PD-A3", "code": "PD-A3", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "P-054", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "P-054"}},
            {"nom": "Démarreur Moteur DVA-03", "code": "DVA-03", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-9"}},
            {"nom": "Variateur de vitesse POT-VA-03", "code": "POT-VA-03", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}}
        ],
        "021": [
            {"nom": "AÉROTHERME A-021", "code": "A-021", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-4", "MARQUE": "ROSEMEX", "MODÈLE": "H-18", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,10", "DÉBIT AIR (L/S)": "217,00", "PUISSANCE (KW)": "4,022107474472", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,05", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-4"}},
            {"nom": "DRAINS DE PLANCHER AS-2", "code": "AS-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-BF", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "DISPOSITIF ANTIREFOULEMENT DAR-1", "code": "DAR-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "350 XL", "RÉSEAU DE TUYAUTERIE": "Eau Froide Potable", "FT / DA": "FT-MEC022-0"}},
            {"nom": "DISPOSITIF ANTIREFOULEMENT DAR-2", "code": "DAR-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "350 XL", "RÉSEAU DE TUYAUTERIE": "Eau Froide Potable", "FT / DA": "FT-MEC022-0"}},
            {"nom": "ÉCHANGEUR ECH-01", "code": "ECH-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "AMSTRONG", "MODÈLE": "AHRI 18.9G-A", "RÉSEAU DE TUYAUTERIE": "Eau Chaude Potable", "FT / DA": "FT-MEC034-0"}},
            {"nom": "POMPE PE-01", "code": "PE-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "Prédécesseur Électrique": "PD-1", "MARQUE": "GRUNFOS", "MODÈLE": "CMBE 5-62-U-C-E-D-F", "RÉSEAU DE TUYAUTERIE": "Eau Froide Potable", "FT / DA": "FT-MEC020-0", "DÉBIT LIQUIDE (L/S)": "1,7", "TÊTE (KPA)": "157", "TEMPÉRATURE MOYENNE (oC)": "15", "VITESSE (RPM)": "3600", "MOTEUR (HP)": "2", "Vérification VPO": "RI-LFG-29", "Prérequis": "DPE-01"}},
            {"nom": "POMPE PE-02", "code": "PE-02", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "Prédécesseur Électrique": "PE-1", "MARQUE": "ARMSTRONG", "MODÈLE": "E7-2B", "RÉSEAU DE TUYAUTERIE": "Eau Chaude Potable", "FT / DA": "FT-MEC025-0", "DÉBIT LIQUIDE (L/S)": "0,7", "TÊTE (KPA)": "11,5", "TEMPÉRATURE MOYENNE (oC)": "65", "VITESSE (RPM)": "3600", "MOTEUR (HP)": "0,0625", "Vérification VPO": "RI-LFG-29", "Prérequis": "DPE-02"}},
            {"nom": "RÉSERVOIR D'EAU POTABLE R-1", "code": "R-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "NORWESCO", "MODÈLE": "44945", "RÉSEAU DE TUYAUTERIE": "Eau Froide Potable", "FT / DA": "FT-MEC002-A", "VOLUME RÉSERVOIR (L)": "1887"}},
            {"nom": "RÉSERVOIR D'EAU CHAUDE REC-1", "code": "REC-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "AO-SMITH", "MODÈLE": "TJ-80S", "RÉSEAU DE TUYAUTERIE": "Eau Chaude Potable", "FT / DA": "FT-MEC018-0"}},
            {"nom": "RÉSERVOIR D'EXPANSION REX-1", "code": "REX-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "AMTROL", "MODÈLE": "ST-12C", "RÉSEAU DE TUYAUTERIE": "Eau Froide Potable", "FT / DA": "FT-MEC019-0"}},
            {"nom": "ROBINET MOTORISÉ RM-021A", "code": "RM-021A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "26,89", "DIAMÈTRE (MM)": "26,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-021B", "code": "RM-021B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B210", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,20", "PERTE DE PRESSION (KPA)": "46,19", "DIAMÈTRE (MM)": "46,19", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "Démarreur Moteur DPE-01", "code": "DPE-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-4"}},
            {"nom": "Démarreur Moteur DPE-02", "code": "DPE-02", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-4"}}
        ],
        "020": [
            {"nom": "DRAINS DE PLANCHER AS-1", "code": "AS-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-B5", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "CABINETS D'AISANCE CA-1", "code": "CA-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "MANSFIELD", "MODÈLE": "ALTO 135-170", "RÉSEAU DE TUYAUTERIE": "Eau Froide Potable & Évent", "FT / DA": "FT-MEC008-0", "DÉBIT LIQUIDE (L/S)": "6"}},
            {"nom": "PLINTHES DE CHAUFFAGE P-020", "code": "P-020", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "0,84", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "67", "LONGUEUR SERPENTIN (MM)": "914", "LONGUEUR CABINET (MM)": "1475", "ARRANGEMENT": "D -> H", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "ROBINET MOTORISÉ RM-020", "code": "RM-020", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "27,72", "DIAMÈTRE (MM)": "27,72", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "URINOIR U-1", "code": "U-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "Z5755-U", "RÉSEAU DE TUYAUTERIE": "Eau Froide Potable & Évent", "FT / DA": "FT-MEC009-0", "DÉBIT LIQUIDE (L/S)": "1,9"}}
        ],
        "022": [
            {"nom": "DRAINS DE PLANCHER AS-1", "code": "AS-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-B5", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "CUVE CU-1", "code": "CU-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "Z1996-24", "RÉSEAU DE TUYAUTERIE": "Eau Chaude Potable & Eau Froide Potable & Évent", "FT / DA": "FT-MEC010-0", "Vérification d'état": "FT-MEC-010"}}
        ],
        "009": [
            {"nom": "DRAINS DE PLANCHER AS-2", "code": "AS-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-BF", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "PLINTHES DE CHAUFFAGE P-009", "code": "P-009", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "0,76", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "68", "LONGUEUR SERPENTIN (MM)": "1067", "LONGUEUR CABINET (MM)": "3214", "ARRANGEMENT": "B", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "ROBINET MOTORISÉ RM-009A", "code": "RM-009A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "27,72", "DIAMÈTRE (MM)": "27,72", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-009B", "code": "RM-009B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}}
        ],
        "010": [
            {"nom": "DRAINS DE PLANCHER AS-2", "code": "AS-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-BF", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "ROBINET MOTORISÉ RM-012A", "code": "RM-012A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B318", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,97", "PERTE DE PRESSION (KPA)": "29,99", "DIAMÈTRE (MM)": "29,99", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-012B", "code": "RM-012B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B318", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,97", "PERTE DE PRESSION (KPA)": "29,99", "DIAMÈTRE (MM)": "29,99", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "Unité de ventilation UV-02", "code": "UV-02", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-4", "MODÈLE": "ALDES PA15", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "Ctrl-Int-UV-02"}},
            {"nom": "Contrôle Interne Ctrl-Int-UV-02", "code": "Ctrl-Int-UV-02", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité/Contrôle", "Prérequis": "PE-4"}}
        ],
        "019": [
            {"nom": "DRAINS DE PLANCHER AS-2", "code": "AS-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-BF", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "DRAINS DE PLANCHER AS-2", "code": "AS-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-BF", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "DRAINS DE PLANCHER AS-2", "code": "AS-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-BF", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "AÉROCONVECTEUR C-019A", "code": "C-019A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-4", "MARQUE": "ROSEMEX", "MODÈLE": "F-300-A", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-007-0", "DÉBIT LIQUIDE (L/S)": "0,1", "DÉBIT AIR (L/S)": "94", "PUISSANCE (KW)": "4,129078417942", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,07", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-4"}},
            {"nom": "AÉROCONVECTEUR C-019B", "code": "C-019B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-4", "MARQUE": "ROSEMEX", "MODÈLE": "F-300-A", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-007-0", "DÉBIT LIQUIDE (L/S)": "0,1", "DÉBIT AIR (L/S)": "94", "PUISSANCE (KW)": "4,129078417942", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,07", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-4"}},
            {"nom": "ROBINET MOTORISÉ RM-019A", "code": "RM-019A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "51,09", "DIAMÈTRE (MM)": "51,09", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-019B", "code": "RM-019B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "51,09", "DIAMÈTRE (MM)": "51,09", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}}
        ],
        "001": [
            {"nom": "AÉROCONVECTEUR C-001", "code": "C-001", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-4", "MARQUE": "ROSEMEX", "MODÈLE": "F-300-A", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-007-0", "DÉBIT LIQUIDE (L/S)": "0,1", "DÉBIT AIR (L/S)": "94", "PUISSANCE (KW)": "4,129078417942", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,07", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-4"}},
            {"nom": "ROBINET MOTORISÉ RM-001", "code": "RM-001", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "51,09", "DIAMÈTRE (MM)": "51,09", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}}
        ],
        "ESC-01": [
            {"nom": "AÉROCONVECTEUR C-ESC1", "code": "C-ESC1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "F-300-A", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-007-0", "DÉBIT LIQUIDE (L/S)": "0,1", "DÉBIT AIR (L/S)": "94", "PUISSANCE (KW)": "4,129078417942", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,07", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-4"}},
            {"nom": "ROBINET MOTORISÉ RM-ESC1", "code": "RM-ESC1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "51,09", "DIAMÈTRE (MM)": "51,09", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}}
        ],
        "ESC-02": [
            {"nom": "AÉROCONVECTEUR C-ESC2", "code": "C-ESC2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "F-300-A", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-007-0", "DÉBIT LIQUIDE (L/S)": "0,1", "DÉBIT AIR (L/S)": "94", "PUISSANCE (KW)": "4,129078417942", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,07", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-4"}},
            {"nom": "ROBINET MOTORISÉ RM-ESC2", "code": "RM-ESC2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "51,09", "DIAMÈTRE (MM)": "51,09", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}}
        ],
        "002": [
            {"nom": "FOSSE SEPTIQUE FS-1", "code": "FS-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ROTO-SPEC", "MODÈLE": "RS-6003R-18", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC001-0", "DÉBIT LIQUIDE (L/S)": "1,66", "VOLUME RÉSERVOIR (L)": "2424"}}
        ],
        "012": [
            {"nom": "ROBINET PRISE D'EAU INTÉRIEUR RA-1", "code": "RA-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "Z1341", "RÉSEAU DE TUYAUTERIE": "Eau Froide Service", "FT / DA": "FT-MEC017-0"}},
            {"nom": "Panneau de Distribution PD-2", "code": "PD-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PD-1", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "PD-1"}},
            {"nom": "Panneau de Distribution PE-4", "code": "PE-4", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PE-1", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "PD-1"}}
        ]
    },
    "niveau2": {
        "106": [
            {"nom": "AÉROTHERME A-106", "code": "A-106", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-6", "MARQUE": "ROSEMEX", "MODÈLE": "H-18", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,10", "DÉBIT AIR (L/S)": "217,00", "PUISSANCE (KW)": "4,022107474472", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,05", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-6"}},
            {"nom": "DRAINS DE PLANCHER AS-2", "code": "AS-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-BF", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "DRAINS DE PLANCHER AS-2", "code": "AS-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-BF", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "DISPOSITIF ANTIREFOULEMENT DAR-3", "code": "DAR-3", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "350 XL", "RÉSEAU DE TUYAUTERIE": "Eau Froide Potable", "FT / DA": "FT-MEC022-0"}},
            {"nom": "POMPE PG-01", "code": "PG-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "CCM-1", "MARQUE": "ARMSTRONG", "MODÈLE": "4300 - 3x3x10-4p", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "FT / DA": "FT-MEC-026-A", "DÉBIT LIQUIDE (L/S)": "15,1", "TÊTE (KPA)": "224", "TEMPÉRATURE MOYENNE (oC)": "77", "VITESSE (RPM)": "1765", "MOTEUR (HP)": "7,5", "DIAMÈTRE IMPULSEUR (MM)": "230", "Vérification VPO": "RI-LFG-29", "Prérequis": "DPG-01"}},
            {"nom": "POMPE PG-02", "code": "PG-02", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "CCM-1", "MARQUE": "ARMSTRONG", "MODÈLE": "4300 - 3x3x10-4p", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "FT / DA": "FT-MEC-026-A", "DÉBIT LIQUIDE (L/S)": "15,1", "TÊTE (KPA)": "224", "TEMPÉRATURE MOYENNE (oC)": "77", "VITESSE (RPM)": "1765", "MOTEUR (HP)": "7,5", "DIAMÈTRE IMPULSEUR (MM)": "230", "Vérification VPO": "RI-LFG-29", "Prérequis": "DPG-02"}},
            {"nom": "POMPE PG-03", "code": "PG-03", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "CCM-1", "MARQUE": "ARMSTRONG", "MODÈLE": "4380- 3x3x10-4p", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-026-A", "DÉBIT LIQUIDE (L/S)": "11,9", "TÊTE (KPA)": "179", "TEMPÉRATURE MOYENNE (oC)": "77", "VITESSE (RPM)": "1765", "MOTEUR (HP)": "5", "DIAMÈTRE IMPULSEUR (MM)": "203", "Vérification VPO": "RI-LFG-29", "Prérequis": "DPG-03"}},
            {"nom": "POMPE PG-04", "code": "PG-04", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "CCM-1", "MARQUE": "ARMSTRONG", "MODÈLE": "4380- 3x3x10-4p", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-026-A", "DÉBIT LIQUIDE (L/S)": "11,9", "TÊTE (KPA)": "179", "TEMPÉRATURE MOYENNE (oC)": "77", "VITESSE (RPM)": "1765", "MOTEUR (HP)": "5", "DIAMÈTRE IMPULSEUR (MM)": "203", "Vérification VPO": "RI-LFG-29", "Prérequis": "DPG-04"}},
            {"nom": "RÉSERVOIRS D'EXPANSION REX-01", "code": "REX-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "AMTROL EXTROL", "MODÈLE": "AX-120V", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "FT / DA": "FT-MEC-028", "PRESSION DE REMPLISSAGE (KPA)": "82,7", "PRESSION MAXIMUM (KPA)": "344,7", "PRESSION D'AJUSTEMENT SOUPAPE SÛRETÉ (KPA)": "689", "TEMPÉRATURE MIN (oC)": "5", "TEMPÉRATURE MAX (oC)": "100", "VOLUME RÉSERVOIR (L)": "257", "CAPACITÉ (L)": "128,7", "DIAMÈTRE (MM)": "610", "HAUTEUR (MM)": "1194"}},
            {"nom": "RÉSERVOIRS D'EXPANSION REX-02", "code": "REX-02", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "AMTROL EXTROL", "MODÈLE": "AX-120V", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "FT / DA": "FT-MEC-028", "PRESSION DE REMPLISSAGE (KPA)": "82,7", "PRESSION MAXIMUM (KPA)": "344,7", "PRESSION D'AJUSTEMENT SOUPAPE SÛRETÉ (KPA)": "689", "TEMPÉRATURE MIN (oC)": "5", "TEMPÉRATURE MAX (oC)": "100", "VOLUME RÉSERVOIR (L)": "257", "CAPACITÉ (L)": "128,7", "DIAMÈTRE (MM)": "610", "HAUTEUR (MM)": "1194"}},
            {"nom": "ROBINET MOTORISÉ RM-100A", "code": "RM-100A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B318", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "1,05", "PERTE DE PRESSION (KPA)": "35,09", "DIAMÈTRE (MM)": "35,09", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-106A", "code": "RM-106A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "26,89", "DIAMÈTRE (MM)": "26,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-106B", "code": "RM-106B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-106C", "code": "RM-106C", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "F7100HD", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "11,89", "PERTE DE PRESSION (KPA)": "4,62", "DIAMÈTRE (MM)": "4,62", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SÉPARATEUR D'AIR SPA-01", "code": "SPA-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "SPIROTHERM", "MODÈLE": "VSR600FA", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "FT / DA": "FT-MEC-029-0", "Vérification d'état": "FT-MEC-029"}},
            {"nom": "RÉSERVOIRS DE PRESSURISATION DE GLYCOL SPG-01", "code": "SPG-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-6", "MARQUE": "CALEFACTO", "MODÈLE": "GMP13100", "RÉSEAU DE TUYAUTERIE": "Boucle B-M (Primaire)", "FT / DA": "FT-MEC-027", "MOTEUR (HP)": "0,33", "CAPACITÉ (L)": "378", "DIAMÈTRE (MM)": "710", "HAUTEUR (MM)": "1700", "Vérification d'état": "FT-MEC-027", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-6"}},
            {"nom": "Ventilateur VA-08", "code": "VA-08", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-6", "MODÈLE": "ACME XD120EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVA-08, POT-VA-08"}},
            {"nom": "Ventilateur VE-08", "code": "VE-08", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-6", "MODÈLE": "ACME XD120EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVE-08, POT-VE-08"}},
            {"nom": "Unité de ventilation UV-03 (VA)", "code": "UV-03 (VA)", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "CCM-1", "MODÈLE": "Dakin CAH006GDGM", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "EFV-01-UV-03"}},
            {"nom": "Unité de ventilation UV-03 (VE)", "code": "UV-03 (VE)", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "CCM-1", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "EFV-02-UV-03"}},
            {"nom": "Panneau de Distribution PE-6", "code": "PE-6", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PE-1", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "PD-1"}},
            {"nom": "Centre de Commande de Moteurs CCM-1", "code": "CCM-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PD-1", "Vérification d'état": "RIC-APP16225", "Vérification VPO": "RIC-APP16225", "Prérequis": "PD-1"}},
            {"nom": "Démarreur Moteur DVA-08", "code": "DVA-08", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-6"}},
            {"nom": "Variateur de vitesse POT-VA-08", "code": "POT-VA-08", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Démarreur Moteur DVE-08", "code": "DVE-08", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-6"}},
            {"nom": "Variateur de vitesse POT-VE-08", "code": "POT-VE-08", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Entrainement à Fréquence Variable EFV-01-UV-03", "code": "EFV-01-UV-03", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité/Contrôle", "Prérequis": "CCM-1"}},
            {"nom": "Entrainement à Fréquence Variable EFV-02-UV-03", "code": "EFV-02-UV-03", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité/Contrôle", "Prérequis": "CCM-1"}},
            {"nom": "Démarreur Moteur DPG-01", "code": "DPG-01", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "CCM-1"}},
            {"nom": "Démarreur Moteur DPG-02", "code": "DPG-02", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "CCM-1"}},
            {"nom": "Démarreur Moteur DPG-03", "code": "DPG-03", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "CCM-1"}},
            {"nom": "Démarreur Moteur DPG-04", "code": "DPG-04", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "CCM-1"}},
            {"nom": "Panneau de Contrôle SGB", "code": "SGB", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Prédécesseur Électrique": "PEU-1", "Prérequis": "PEU-1"}}
        ],
        "108": [
            {"nom": "AÉROTHERME A-108", "code": "A-108", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "Prédécesseur Électrique": "PE-2", "MARQUE": "ROSEMEX", "MODÈLE": "H-18", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-005-0", "DÉBIT LIQUIDE (L/S)": "0,10", "DÉBIT AIR (L/S)": "217,00", "PUISSANCE (KW)": "4,022107474472", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "MOTEUR (HP)": "0,05", "Vérification d'état": "RIC-BAT632-9", "Vérification VPO": "RIC-BAT634-2", "Prérequis": "PE-2"}},
            {"nom": "ROBINET MOTORISÉ RM-108", "code": "RM-108", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "26,89", "DIAMÈTRE (MM)": "26,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "Ventilateur VA-09", "code": "VA-09", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-2", "MODÈLE": "ACME XD161EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVA-09, POT-VA-09"}},
            {"nom": "Ventilateur VE-09", "code": "VE-09", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-2", "MODÈLE": "ACME XD161EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVE-09, POT-VE-09"}},
            {"nom": "Panneau de Distribution P-054", "code": "P-054", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-APP16235", "Vérification VPO": "RIC-APP16235"}},
            {"nom": "Panneau de Distribution PD-1", "code": "PD-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "P-054", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "P-054"}},
            {"nom": "Panneau de Distribution PE-1", "code": "PE-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PD-1", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "PD-1"}},
            {"nom": "Panneau de Distribution PE-2", "code": "PE-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PE-1", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "PE-1"}},
            {"nom": "Panneau de Distribution PE-3", "code": "PE-3", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PD-1", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "PD-1"}},
            {"nom": "Panneau de Distribution P-055", "code": "P-055", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PM-2", "Vérification d'état": "RIC-APP16235", "Vérification VPO": "RIC-APP16235", "Prérequis": "PM-2"}},
            {"nom": "Panneau de Distribution PEU-1", "code": "PEU-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "P-055", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "P-055"}},
            {"nom": "Démarreur Moteur DVA-09", "code": "DVA-09", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-2"}},
            {"nom": "Variateur de vitesse POT-VA-09", "code": "POT-VA-09", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}},
            {"nom": "Démarreur Moteur DVE-09", "code": "DVE-09", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-2"}},
            {"nom": "Variateur de vitesse POT-VE-09", "code": "POT-VE-09", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}}
        ],
        "113": [
            {"nom": "DRAINS DE PLANCHER AS-1", "code": "AS-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "ZN415-B5", "RÉSEAU DE TUYAUTERIE": "Évent", "FT / DA": "FT-MEC014-0"}},
            {"nom": "BOÎTIER DE LESSIVEUSE BL-1", "code": "BL-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "SIOUX CHEF", "MODÈLE": "696RG2313MF", "RÉSEAU DE TUYAUTERIE": "Eau Chaude Potable & Eau Froide Potable & Évent", "FT / DA": "FT-MEC015-0"}},
            {"nom": "CABINETS D'AISANCE CA-1", "code": "CA-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "MANSFIELD", "MODÈLE": "ALTO 135-170", "RÉSEAU DE TUYAUTERIE": "Eau Froide Potable & Évent", "FT / DA": "FT-MEC008-0", "DÉBIT LIQUIDE (L/S)": "1,9"}},
            {"nom": "ÉVIER E-2", "code": "E-2", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "KINDRED", "MODÈLE": "QSLA2031-8-1", "RÉSEAU DE TUYAUTERIE": "Eau Chaude Potable & Eau Froide Potable & Évent", "FT / DA": "FT-MEC012-0", "DÉBIT LIQUIDE (L/S)": "6,8"}},
            {"nom": "LAVABO L-1", "code": "L-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "Z5114", "RÉSEAU DE TUYAUTERIE": "Eau Chaude Potable & Eau Froide Potable & Évent", "FT / DA": "FT-MEC013-A", "DÉBIT LIQUIDE (L/S)": "5,7"}},
            {"nom": "PLINTHES DE CHAUFFAGE P-113", "code": "P-113", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "1,4", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "LONGUEUR SERPENTIN (MM)": "1524", "LONGUEUR CABINET (MM)": "1891", "ARRANGEMENT": "D -> H", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "ROBINET MOTORISÉ RM-113A", "code": "RM-113A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "52,33", "DIAMÈTRE (MM)": "52,33", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-113B", "code": "RM-113B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "Ventilateur VE-11", "code": "VE-11", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-6", "MODÈLE": "ACME XD100EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVE-11, POT-VE-11"}},
            {"nom": "Démarreur Moteur DVE-11", "code": "DVE-11", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-6"}},
            {"nom": "Variateur de vitesse POT-VE-11", "code": "POT-VE-11", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}}
        ],
        "110": [
            {"nom": "CUVE CU-1", "code": "CU-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ZURN", "MODÈLE": "Z1996-24", "RÉSEAU DE TUYAUTERIE": "Eau Chaude Potable & Eau Froide Potable & Évent", "FT / DA": "FT-MEC010-0", "Vérification d'état": "FT-MEC-010"}},
            {"nom": "PLINTHES DE CHAUFFAGE P-110", "code": "P-110", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "0,43", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "72", "LONGUEUR SERPENTIN (MM)": "610", "LONGUEUR CABINET (MM)": "1200", "ARRANGEMENT": "B", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "ROBINET MOTORISÉ RM-110", "code": "RM-110", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "27,72", "DIAMÈTRE (MM)": "27,72", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}}
        ],
        "100": [
            {"nom": "DOUCHE OCULAIRE DO-1", "code": "DO-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "BRADLEY", "MODÈLE": "S19-690", "RÉSEAU DE TUYAUTERIE": "N/A", "FT / DA": "FT-MEC016-A"}},
            {"nom": "ROBINET MOTORISÉ RM-006", "code": "RM-006", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B209", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,09", "PERTE DE PRESSION (KPA)": "24,20", "DIAMÈTRE (MM)": "24,20", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-100B", "code": "RM-100B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B209", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,14", "PERTE DE PRESSION (KPA)": "52,54", "DIAMÈTRE (MM)": "52,54", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-08", "code": "SC-08", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BS0801B", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "UV-03", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,14", "PERTE DE PRESSION (KPA)": "16,4", "PUISSANCE (KW)": "5,726022721964", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "65", "Vérification d'état": "RIC-BAT632-7"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-14", "code": "SC-14", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BB1201B", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "UV-03", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,09", "PERTE DE PRESSION (KPA)": "0,6", "PUISSANCE (KW)": "1,253465000606", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "73", "Vérification d'état": "RIC-BAT632-7"}}
        ],
        "102": [
            {"nom": "ÉVIER E-1", "code": "E-1", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Plomberie", "MARQUE": "ELKAY", "MODÈLE": "DSE133221-D1125", "RÉSEAU DE TUYAUTERIE": "Eau Chaude Potable & Eau Froide Potable & Évent", "FT / DA": "FT-MEC012-0", "DÉBIT LIQUIDE (L/S)": "6,8"}},
            {"nom": "PLINTHES DE CHAUFFAGE P-102", "code": "P-102", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "1,12", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "LONGUEUR SERPENTIN (MM)": "1219", "LONGUEUR CABINET (MM)": "3346", "ARRANGEMENT": "D -> H", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "ROBINET MOTORISÉ RM-102A", "code": "RM-102A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B209", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,09", "PERTE DE PRESSION (KPA)": "24,27", "DIAMÈTRE (MM)": "24,27", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-102B", "code": "RM-102B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,20", "PERTE DE PRESSION (KPA)": "46,19", "DIAMÈTRE (MM)": "46,19", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-09", "code": "SC-09", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BS0601B", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "UV-03", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,09", "PERTE DE PRESSION (KPA)": "3,3", "PUISSANCE (KW)": "1,558258921726", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "72", "Vérification d'état": "RIC-BAT632-7"}}
        ],
        "103": [
            {"nom": "PLINTHES DE CHAUFFAGE P-103A", "code": "P-103A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "1,12", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "LONGUEUR SERPENTIN (MM)": "1219", "LONGUEUR CABINET (MM)": "1947", "ARRANGEMENT": "D -> H", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "PLINTHES DE CHAUFFAGE P-103B", "code": "P-103B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "1,12", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "LONGUEUR SERPENTIN (MM)": "1219", "LONGUEUR CABINET (MM)": "3460", "ARRANGEMENT": "D -> H", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "ROBINET MOTORISÉ RM-103A", "code": "RM-103A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B209", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "27,85", "DIAMÈTRE (MM)": "27,85", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-103B", "code": "RM-103B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "33,72", "DIAMÈTRE (MM)": "33,72", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-103C", "code": "RM-103C", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "33,72", "DIAMÈTRE (MM)": "33,72", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-10", "code": "SC-10", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BS0701B", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "UV-03", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,10", "PERTE DE PRESSION (KPA)": "3,9", "PUISSANCE (KW)": "2,364497457304", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "70", "Vérification d'état": "RIC-BAT632-7"}}
        ],
        "104": [
            {"nom": "PLINTHES DE CHAUFFAGE P-104B", "code": "P-104B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,05", "PUISSANCE (KW)": "1,68", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "67", "LONGUEUR SERPENTIN (MM)": "1828", "LONGUEUR CABINET (MM)": "2671", "ARRANGEMENT": "D -> H", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "ROBINET MOTORISÉ RM-104A", "code": "RM-104A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B208", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,09", "PERTE DE PRESSION (KPA)": "65,29", "DIAMÈTRE (MM)": "65,29", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-104B", "code": "RM-104B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,05", "PERTE DE PRESSION (KPA)": "27,72", "DIAMÈTRE (MM)": "27,72", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-11", "code": "SC-11", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BS0601B", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "UV-03", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,09", "PERTE DE PRESSION (KPA)": "3,0", "PUISSANCE (KW)": "1,52103889482", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "72", "Vérification d'état": "RIC-BAT632-7"}}
        ],
        "105": [
            {"nom": "PLINTHES DE CHAUFFAGE P-105", "code": "P-105", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "0,7", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "69", "LONGUEUR SERPENTIN (MM)": "762", "LONGUEUR CABINET (MM)": "1220", "ARRANGEMENT": "D -> H", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "ROBINET MOTORISÉ RM-105", "code": "RM-105", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "27,72", "DIAMÈTRE (MM)": "27,72", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}}
        ],
        "107": [
            {"nom": "PLINTHES DE CHAUFFAGE P-107A", "code": "P-107A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "1,4", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "LONGUEUR SERPENTIN (MM)": "1524", "LONGUEUR CABINET (MM)": "4101", "ARRANGEMENT": "D -> H", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "PLINTHES DE CHAUFFAGE P-107B", "code": "P-107B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "1,4", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "66", "LONGUEUR SERPENTIN (MM)": "1524", "LONGUEUR CABINET (MM)": "3738", "ARRANGEMENT": "D -> H", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "ROBINET MOTORISÉ RM-107A", "code": "RM-107A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B209", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,09", "PERTE DE PRESSION (KPA)": "24,20", "DIAMÈTRE (MM)": "24,20", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-107B", "code": "RM-107B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "52,33", "DIAMÈTRE (MM)": "52,33", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-107C", "code": "RM-107C", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "52,33", "DIAMÈTRE (MM)": "52,33", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-107D", "code": "RM-107D", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "42,89", "DIAMÈTRE (MM)": "42,89", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-12", "code": "SC-12", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BB1001B", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "UV-03", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,09", "PERTE DE PRESSION (KPA)": "0,6", "PUISSANCE (KW)": "1,035420118574", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "74", "Vérification d'état": "RIC-BAT632-7"}}
        ],
        "109": [
            {"nom": "PLINTHES DE CHAUFFAGE P-109", "code": "P-109", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "0,43", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "72", "LONGUEUR SERPENTIN (MM)": "610", "LONGUEUR CABINET (MM)": "1900", "ARRANGEMENT": "B", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "ROBINET MOTORISÉ RM-109A", "code": "RM-109A", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "B209", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,09", "PERTE DE PRESSION (KPA)": "24,20", "DIAMÈTRE (MM)": "24,20", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "ROBINET MOTORISÉ RM-109B", "code": "RM-109B", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "27,72", "DIAMÈTRE (MM)": "27,72", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "SERPENTINS DE CHAUFFAGE HYDRONIQUE SC-13", "code": "SC-13", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "DAIKIN", "MODÈLE": "5BB0901C", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "SYSTÈME VENTILATION": "UV-03", "FT / DA": "FT-VEN-002rA", "DÉBIT LIQUIDE (L/S)": "0,09", "PERTE DE PRESSION (KPA)": "0,6", "PUISSANCE (KW)": "0,579987663362", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "75", "Vérification d'état": "RIC-BAT632-7"}}
        ],
        "111": [
            {"nom": "PLINTHES DE CHAUFFAGE P-111", "code": "P-111", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "ROSEMEX", "MODÈLE": "RVS-RAF44C1", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "FT / DA": "FT-MEC-006-A", "DÉBIT LIQUIDE (L/S)": "0,03", "PUISSANCE (KW)": "0,43", "TEMPÉRATURE ENTRÉE (oC)": "77", "TEMPÉRATURE SORTIE (oC)": "72", "LONGUEUR SERPENTIN (MM)": "610", "LONGUEUR CABINET (MM)": "1410", "ARRANGEMENT": "B", "Vérification d'état": "RI-LFG-20-2"}},
            {"nom": "ROBINET MOTORISÉ RM-111", "code": "RM-111", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Mécanique", "MARQUE": "BELIMO", "MODÈLE": "Z2050Q-F", "RÉSEAU DE TUYAUTERIE": "Boucle de chauffage (secondaire)", "DÉBIT LIQUIDE (L/S)": "0,03", "PERTE DE PRESSION (KPA)": "27,72", "DIAMÈTRE (MM)": "27,72", "Vérification VPO": "IntégrAir-Séquence", "Prérequis": "SGB"}},
            {"nom": "Ventilateur VE-12", "code": "VE-12", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Ventilation", "Prédécesseur Électrique": "PE-6", "MODÈLE": "ACME XD100EC", "Vérification d'état": "RIC-BAT632-3", "Vérification VPO": "PSM-MES-1", "Prérequis": "DVE-012, POT-VE-12"}},
            {"nom": "Démarreur Moteur DVE-012", "code": "DVE-012", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Vérification d'état": "RIC-BAT634-1a", "Vérification VPO": "RIC-BAT634-1a", "Prérequis": "PE-6"}},
            {"nom": "Variateur de vitesse POT-VE-12", "code": "POT-VE-12", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Contrôle", "Vérification d'état": "RIC-BAT632-3"}}
        ],
        "101": [
            {"nom": "Panneau de Distribution PE-11", "code": "PE-11", "details": {"ÉTAT GÉNÉRAL": "À définir", "DISCIPLINE": "Électricité", "Prédécesseur Électrique": "PE-1", "Vérification d'état": "RIC-BAT634-1", "Vérification VPO": "RIC-BAT634-1", "Prérequis": "PE-1"}}
        ]
    }
};